<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: "Helvetica", Arial, sans-serif; color: #1B2430; font-size: 11.5px; }
        table.kv { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.kv td { padding: 6px 0; border-bottom: 1px solid #DDE3EA; vertical-align: top; }
        table.kv td.label { width: 160px; color: #44546B; font-weight: bold; font-size: 10.5px; text-transform: uppercase; }
        table.totals { width: 100%; border-collapse: collapse; margin-top: 4px; }
        table.totals td { padding: 6px 9px; border: 1px solid #DDE3EA; }
        table.totals td.label { background: #FAFBFC; font-weight: bold; color: #44546B; width: 70%; }
        table.totals td.value { text-align: right; width: 30%; }
        table.totals tr.grand td { font-weight: bold; font-size: 13px; color: #0E2A47; }
        .status-pill { display: inline-block; padding: 3px 10px; border-radius: 10px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .status-paid { background: #E6F4EC; color: #2F855A; }
        .status-rejected { background: #FBEAEA; color: #C53030; }
        .status-pending { background: #FCF1DF; color: #8A5A0F; }
        .section-title { font-size: 12px; font-weight: bold; color: #0E2A47; text-transform: uppercase; margin: 18px 0 8px; }
        .footer-note { margin-top: 30px; font-size: 9px; color: #8A93A1; border-top: 1px solid #DDE3EA; padding-top: 8px; }
        .reason-box { background: #FBEAEA; border-left: 3px solid #C53030; padding: 10px 12px; font-size: 11px; margin-top: 6px; }
    </style>
</head>
<body>

    @include('pdf.letterhead', ['reportTitle' => 'Invoice Review Report'])

    <table class="kv">
        <tr>
            <td class="label">Invoice No.</td>
            <td>{{ $invoice->Invoice_num }}</td>
            <td class="label">Status</td>
            <td>
                @php
                    $cls = match($invoice->Status) {
                        'Paid' => 'status-paid',
                        'Rejected' => 'status-rejected',
                        default => 'status-pending',
                    };
                @endphp
                <span class="status-pill {{ $cls }}">{{ $invoice->Status }}</span>
            </td>
        </tr>
        <tr>
            <td class="label">Linked DO</td>
            <td>{{ $invoice->deliveryOrder->DO_number ?? '—' }}</td>
            <td class="label">Issue Date</td>
            <td>{{ $invoice->issue_date?->format('d M Y') ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Vendor</td>
            <td>{{ $invoice->supplier->Supplier_name ?? '—' }}</td>
            <td class="label">Handled By</td>
            <td>{{ $invoice->staff->Username ?? 'Unassigned' }}</td>
        </tr>
        <tr>
            <td class="label">Description</td>
            <td colspan="3">{{ $invoice->Description ?? '—' }}</td>
        </tr>
    </table>

    <div class="section-title">Amount Breakdown</div>
    <table class="totals">
        <tr><td class="label">Subtotal</td><td class="value">RM {{ number_format($invoice->Subtotal, 2) }}</td></tr>
        <tr><td class="label">Tax</td><td class="value">RM {{ number_format($invoice->Tax, 2) }}</td></tr>
        <tr><td class="label">Credit Note</td><td class="value">RM {{ number_format($invoice->Credit_note, 2) }}</td></tr>
        <tr class="grand"><td class="label">Total</td><td class="value">RM {{ number_format($invoice->Total, 2) }}</td></tr>
    </table>

    @if($invoice->isRejected())
        <div class="section-title">Rejection Reason</div>
        <div class="reason-box">{{ $invoice->Reason }}</div>
    @endif

    <div class="footer-note">
        This document is system-generated by KTM eDOIS for internal review purposes. Invoice ID: {{ $invoice->Invoice_id }}.
    </div>

</body>
</html>
