<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: "Helvetica", Arial, sans-serif; color: #1B2430; font-size: 11.5px; }
        table.kv { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.kv td { padding: 6px 0; border-bottom: 1px solid #DDE3EA; vertical-align: top; }
        table.kv td.label { width: 160px; color: #44546B; font-weight: bold; font-size: 10.5px; text-transform: uppercase; }
        table.items { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.items th { background: #FAFBFC; border: 1px solid #DDE3EA; padding: 7px 9px; text-align: left; font-size: 10px; text-transform: uppercase; color: #44546B; }
        table.items td { border: 1px solid #DDE3EA; padding: 7px 9px; }
        .status-pill { display: inline-block; padding: 3px 10px; border-radius: 10px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .status-approved { background: #E6F4EC; color: #2F855A; }
        .status-rejected { background: #FBEAEA; color: #C53030; }
        .status-pending { background: #FCF1DF; color: #8A5A0F; }
        .section-title { font-size: 12px; font-weight: bold; color: #0E2A47; text-transform: uppercase; margin: 18px 0 8px; }
        .footer-note { margin-top: 30px; font-size: 9px; color: #8A93A1; border-top: 1px solid #DDE3EA; padding-top: 8px; }
        .reason-box { background: #FBEAEA; border-left: 3px solid #C53030; padding: 10px 12px; font-size: 11px; margin-top: 6px; }
    </style>
</head>
<body>

    @include('pdf.letterhead', ['reportTitle' => 'Delivery Order Review Report'])

    <table class="kv">
        <tr>
            <td class="label">DO Number</td>
            <td>{{ $deliveryOrder->DO_number }}</td>
            <td class="label">Status</td>
            <td>
                @php
                    $cls = match($deliveryOrder->Status) {
                        'Approved' => 'status-approved',
                        'Rejected' => 'status-rejected',
                        default => 'status-pending',
                    };
                @endphp
                <span class="status-pill {{ $cls }}">{{ $deliveryOrder->Status }}</span>
            </td>
        </tr>
        <tr>
            <td class="label">PO Number</td>
            <td>{{ $deliveryOrder->PO_number }}</td>
            <td class="label">Submitted On</td>
            <td>{{ $deliveryOrder->created_date?->format('d M Y, h:i A') ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Vendor</td>
            <td>{{ $deliveryOrder->supplier->Supplier_name ?? '—' }}</td>
            <td class="label">Vendor Number</td>
            <td>{{ $deliveryOrder->supplier->Vendor_number ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Contact Person</td>
            <td>{{ $deliveryOrder->supplier->Contact_person ?? '—' }}</td>
            <td class="label">Reviewing Officer</td>
            <td>{{ $deliveryOrder->staff->Username ?? 'Unassigned' }}</td>
        </tr>
    </table>

    <div class="section-title">Items</div>
    @if($deliveryOrder->items->isEmpty())
        <p style="color:#44546B; font-size:11px;">No line items recorded for this delivery order.</p>
    @else
        <table class="items">
            <thead>
                <tr><th style="width:40px;">#</th><th>Description</th><th style="width:100px;">Quantity</th></tr>
            </thead>
            <tbody>
                @foreach($deliveryOrder->items as $i => $item)
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ $item->item_description }}</td>
                        <td>{{ $item->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    @if($deliveryOrder->isRejected())
        <div class="section-title">Rejection Reason</div>
        <div class="reason-box">{{ $deliveryOrder->Reason }}</div>
    @endif

    <div class="footer-note">
        This document is system-generated by KTM eDOIS for internal review purposes. DO ID: {{ $deliveryOrder->DO_id }}.
    </div>

</body>
</html>
