<?php
/**
 * views/invoice/pdf.php
 * Replaces: resources/views/invoice/pdf.blade.php
 * Same print-to-PDF approach as do/pdf.php
 */

$statusCls = match($inv['Status']) {
    'Paid'     => 'status-paid',
    'Rejected' => 'status-rejected',
    default    => 'status-pending',
};
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice Report — <?= e($inv['Invoice_num']) ?></title>
    <style>
        body { font-family: Arial, sans-serif; color: #1B2430; font-size: 11.5px; margin: 20px; }
        table.kv { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.kv td { padding: 6px 0; border-bottom: 1px solid #DDE3EA; vertical-align: top; }
        table.kv td.label { width: 160px; color: #44546B; font-weight: bold; font-size: 10.5px; text-transform: uppercase; }
        table.totals { width: 100%; border-collapse: collapse; margin-top: 4px; }
        table.totals td { padding: 6px 9px; border: 1px solid #DDE3EA; }
        table.totals td.label { background: #FAFBFC; font-weight: bold; color: #44546B; width: 70%; }
        table.totals td.value { text-align: right; width: 30%; }
        table.totals tr.grand td { font-weight: bold; font-size: 13px; color: #0E2A47; }
        .status-pill { display: inline-block; padding: 3px 10px; border-radius: 10px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .status-paid     { background: #E6F4EC; color: #2F855A; }
        .status-rejected { background: #FBEAEA; color: #C53030; }
        .status-pending  { background: #FCF1DF; color: #8A5A0F; }
        .section-title { font-size: 12px; font-weight: bold; color: #0E2A47; text-transform: uppercase; margin: 18px 0 8px; }
        .footer-note { margin-top: 30px; font-size: 9px; color: #8A93A1; border-top: 1px solid #DDE3EA; padding-top: 8px; }
        .reason-box { background: #FBEAEA; border-left: 3px solid #C53030; padding: 10px 12px; font-size: 11px; margin-top: 6px; }
        hr.thick { border: none; border-top: 2px solid #0E2A47; margin: 12px 0 16px; }
        .report-title { font-size: 14px; font-weight: bold; color: #0E2A47; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 14px; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>

    {{-- Letterhead --}}
    <table style="width:100%; margin-bottom:18px;">
        <tr>
            <td>
                <div style="font-size:16px; font-weight:bold; color:#0E2A47; letter-spacing:1px;">KTM eDOIS</div>
                <div style="font-size:10px; color:#44546B;">Electronic Delivery Order &amp; Invoice System</div>
            </td>
            <td style="text-align:right; font-size:9.5px; color:#44546B;">
                Generated: <?= fmt_datetime(now_str()) ?><br>
                By: <?= e($_SESSION['staff_name'] ?? 'System') ?>
            </td>
        </tr>
    </table>
    <hr class="thick">
    <div class="report-title">Invoice Review Report</div>

    <table class="kv">
        <tr>
            <td class="label">Invoice No.</td>
            <td><?= e($inv['Invoice_num']) ?></td>
            <td class="label">Status</td>
            <td><span class="status-pill <?= $statusCls ?>"><?= e($inv['Status']) ?></span></td>
        </tr>
        <tr>
            <td class="label">Linked DO</td>
            <td><?= e($inv['DO_number'] ?? '—') ?></td>
            <td class="label">Issue Date</td>
            <td><?= fmt_date($inv['issue_date']) ?></td>
        </tr>
        <tr>
            <td class="label">Vendor</td>
            <td><?= e($inv['Supplier_name'] ?? '—') ?></td>
            <td class="label">Handled By</td>
            <td><?= e($inv['handler_name'] ?? 'Unassigned') ?></td>
        </tr>
        <tr>
            <td class="label">Description</td>
            <td colspan="3"><?= e($inv['Description'] ?? '—') ?></td>
        </tr>
    </table>

    <div class="section-title">Amount Breakdown</div>
    <table class="totals">
        <tr><td class="label">Subtotal</td><td class="value"><?= money($inv['Subtotal']) ?></td></tr>
        <tr><td class="label">Tax</td><td class="value"><?= money($inv['Tax']) ?></td></tr>
        <tr><td class="label">Credit Note</td><td class="value"><?= money($inv['Credit_note']) ?></td></tr>
        <tr class="grand"><td class="label">Total</td><td class="value"><?= money($inv['Total']) ?></td></tr>
    </table>

    <?php if ($inv['Status'] === 'Rejected'): ?>
        <div class="section-title">Rejection Reason</div>
        <div class="reason-box"><?= e($inv['Reason'] ?? '') ?></div>
    <?php endif; ?>

    <div class="footer-note">
        This document is system-generated by KTM eDOIS for internal review purposes.
        Invoice ID: <?= e($inv['Invoice_id']) ?>.
    </div>

    <p class="no-print" style="margin-top:24px;">
        <button onclick="window.print()" style="padding:8px 16px; cursor:pointer;">Print / Save as PDF</button>
        <a href="<?= url('invoices/' . $inv['Invoice_id']) ?>" style="margin-left:12px;">← Back</a>
    </p>

    <script>window.onload = function(){ window.print(); };</script>
</body>
</html>
